export const iconMap = {
  workflow: '⚡',
  video: '🎬',
  chatbot: '🤖',
  code: '💻',
  chart: '📊',
  globe: '🌐',
  mail: '📧',
  phone: '📱',
  'arrow-right': '→',
  check: '✓',
  star: '⭐',
  automation: '🔄',
  ai: '🧠',
  rocket: '🚀',
  shield: '🛡️',
  clock: '⏱️',
  users: '👥',
  trending: '📈',
  zap: '⚡',
  settings: '⚙️',
  social: '📱',
  ecommerce: '🛒',
  branding: '🎨',
  content: '✍️',
  consulting: '💡',
  training: '🎓',
  // Widget icons
  bot: '🤖',
  x: '✕',
  whatsapp: '💬',
  'message-circle': '💬',
  send: '➤',
  gift: '🎁',
  lock: '🔒',
  'alert-circle': '⚠️',
  cart: '🛒',
  crm: '📋',
  // Navigation & UI icons
  image: '🖼️',
  expand: '↗️',
  'chevron-left': '‹',
  'chevron-right': '›',
  quote: '"',
  chat: '💬',
  blueprint: '📐',
  plus: '+',
  minus: '-',
};

export function getIcon(name) {
  return iconMap[name] || '🔹';
}
